const express= require('express')
const router = express.Router()
const userController = require("../controllers/user.controller")
router.get('/nav',userController.displaynav)
router.get("/", userController.displayOne)
router.post('/signup',userController.displaySignup)
router.post("/signin",userController.displaySignin)
router.post('/uploads',userController.uploadFile)
router.get('/displayimg',userController.displayUpload)
router.get('/profile',userController.displayProfile)
router.get('/details',userController.displayDb)
router.get('/update', userController.displayUpdate)
module.exports= router